apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ocs-tls-profiles
  name: ocs-tls-profiles-tlsprofile-editor-role
rules:
- apiGroups:
  - ocs.openshift.io
  resources:
  - tlsprofiles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ocs.openshift.io
  resources:
  - tlsprofiles/status
  verbs:
  - get
